package javascript

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"testing"
)

func BenchmarkParseYarnV1LockFile(b *testing.B) {
	yarnV1Content, err := os.ReadFile("test-fixtures/yarn/yarn.lock")
	if err != nil {
		b.Fatalf("failed to read test fixture: %v", err)
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		reader := bytes.NewReader(yarnV1Content)
		_, err := parseYarnV1LockFile(reader)
		if err != nil {
			b.Fatalf("failed to parse yarn v1 lockfile: %v", err)
		}
	}
}

func BenchmarkParseYarnV1LockFile_Large(b *testing.B) {
	content := generateLargeYarnV1Lockfile(1000)

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		reader := strings.NewReader(content)
		_, err := parseYarnV1LockFile(reader)
		if err != nil {
			b.Fatalf("failed to parse yarn v1 lockfile: %v", err)
		}
	}
}

func BenchmarkParseYarnV1LockFile_VeryLarge(b *testing.B) {
	content := generateLargeYarnV1Lockfile(5000)

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		reader := strings.NewReader(content)
		_, err := parseYarnV1LockFile(reader)
		if err != nil {
			b.Fatalf("failed to parse yarn v1 lockfile: %v", err)
		}
	}
}

func BenchmarkParseYarnV1LockFile_Memory(b *testing.B) {
	content := generateLargeYarnV1Lockfile(5000)

	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		reader := strings.NewReader(content)
		_, err := parseYarnV1LockFile(reader)
		if err != nil {
			b.Fatalf("failed to parse yarn v1 lockfile: %v", err)
		}
	}
}

func generateLargeYarnV1Lockfile(numPackages int) string {
	var sb strings.Builder
	sb.WriteString("# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n")
	sb.WriteString("# yarn lockfile v1\n\n")

	for i := 0; i < numPackages; i++ {
		escapedName := fmt.Sprintf("\"package-%d@^1.0.0\":", i)
		version := fmt.Sprintf("1.0.%d", i)

		sb.WriteString(escapedName)
		sb.WriteString("\n")
		sb.WriteString(fmt.Sprintf("  version \"%s\"\n", version))
		sb.WriteString(fmt.Sprintf("  resolved \"https://registry.yarnpkg.com/package-%d/-/package-%d-%s.tgz#1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef\"\n", i, i, version))
		sb.WriteString(fmt.Sprintf("  integrity sha512-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n"))
		sb.WriteString("\n")
	}

	return sb.String()
}
